import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { Sidebar } from "@/components/Layouts/sidebar";
import { Header } from "@/components/Layouts/header";
import { Toaster } from "@/components/ui/toaster";

import { Inter, Suwannaphum } from "next/font/google";
import StoreProvider from "@/app/StoreProvider";
import { Providers } from "@/app/providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
        <Providers>
          <div className="flex min-h-screen">
            
            <div className="w-full bg-gray-2 dark:bg-[#020d1a]">
              
              <main className="isolate mx-auto w-full max-w-screen-2xl overflow-hidden p-4 md:p-7.5">
                {children}
              </main>
            </div>
          </div>
          <Toaster />
        </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
