import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

import { Sidebar } from "@/components/Layouts/sidebar";
import { Header } from "@/components/Layouts/header";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/app/providers";
import StoreProvider from "@/app/StoreProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
        <Providers>
          <div className="flex min-h-screen">
            <div className="w-full bg-slate-100 dark:bg-[#020d1a]">
              <main className="isolate mx-auto w-full  ">
                {children}
              </main>
            </div>
          </div>
          <Toaster />
        </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
